export const C = {
  bg: "#F0F4FA",
  sidebar: "#0D1B2A",
  sidebarHover: "#1a2e44",
  accent: "#1E88C8",
  accentDark: "#0a6daa",
  white: "#fff",
  border: "#E2E8F0",
  text: "#1A202C",
  muted: "#718096",
  success: "#16A34A",
  successBg: "#DCFCE7",
  warn: "#D97706",
  warnBg: "#FEF3DC",
  danger: "#DC2626",
  dangerBg: "#FEE2E2",
  info: "#0a6daa",
  infoBg: "#EBF5F5",
  card: "#fff",
  poppins: "'Poppins','system-ui',sans-serif",
  sans: "'Outfit','system-ui',sans-serif",
};

export const TAG_COLORS = {
  "BIS":        { bg: "#FEF3DC", text: "#9A5C06" },
  "BIS Update": { bg: "#FEF3DC", text: "#9A5C06" },
  "EPR":        { bg: "#DCFCE7", text: "#166534" },
  "WPC":        { bg: "#EBF5F5", text: "#074D4D" },
  "TEC":        { bg: "#EDE9FE", text: "#5b21b6" },
  "BEE":        { bg: "#FEF3C7", text: "#92400e" },
  "LMPC":       { bg: "#FFE4E6", text: "#9f1239" },
  "ISO":        { bg: "#EBF5F5", text: "#0E8080" },
  "CDSCO":      { bg: "#FDF2F8", text: "#9d174d" },
};

export const EMPTY_BLOG = {
  title: "",
  slug: "",
  excerpt: "",
  tag: "BIS",
  date: "",
  readTime: "5 min read",
  author: "Compliance & Regulatory Team",
  featured: false,
  status: "draft",
  img: "",
  heroImg: "",
  heroGradient: "linear-gradient(135deg,rgba(13,27,42,0.97) 0%,rgba(10,109,170,0.82) 100%)",
  highlights: [],
  toc: [],
  meta: [],
  sections: [],
  tags: [],
  related: [],
  sidebarCta: { title: "", body: "", btn: "" },
  ctaTitle: "",
  ctaBody: "",
  seo: {
    metaTitle: "",
    metaDescription: "",
    metaKeywords: [],
    ogTitle: "",
    ogDescription: "",
    ogImage: "",
    canonicalUrl: "",
    noIndex: false,
    structuredData: "",
  },
};
